title: Hello, world! I'm Sanjeevi Kumar
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sanjeevik89.github.io" # Replace with your GitHub Pages URL (e.g., https://yourusername.github.io/my-jekyll-site) IF deploying to a subdirectory. If deploying to the root of your username's page, replace with "https://yourusername.github.io".



# Author Settings
author: Sanjeevi Kumar # add your name
author-img: sanjeevi-kumar.jpg # add your photo
about-author: I am a full stack developer with experience in Angular, Python & MongoDB. I am also an experienced in DevOps, Middleware and Unix Shell development. Always hungry to keep learning. # add description
social-github: sanjeevik89 # add your Github handle
social-linkedin: sanjeevi-kumar # add your Linkedin handle
social-email: sanjeevik89@gmail.com # add your Email address

# # Disqus
# discus-identifier: mr-brown # add your discus identifier

# # Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
